/* Shared TypeScript type definitions for hospital state, patients, departments, metrics, and events. */
export type Severity = "low" | "medium" | "high" | "critical";
export type PatientState =
  | "arriving" | "triage" | "waiting_er" | "in_er"
  | "waiting_labs" | "in_labs" | "waiting_imaging" | "in_imaging"
  | "waiting_icu" | "in_icu" | "waiting_ward" | "in_ward"
  | "waiting_discharge" | "discharged";

export type DepartmentKey = "er" | "labs" | "imaging" | "icu" | "ward" | "discharge";
export type DepartmentStatus = "healthy" | "warning" | "critical";
export type AlertSeverity = "info" | "warning" | "critical";

/**
 * Describes which departments a patient needs to visit during their hospital stay.
 * Each boolean field indicates whether the patient requires that particular step.
 * The imaging_type field specifies which kind of scan is needed if imaging is required.
 */
export interface PatientPathway {
  needs_labs: boolean;
  needs_imaging: boolean;
  needs_icu: boolean;
  needs_ward: boolean;
  imaging_type: "xray" | "ct" | "mri";
}

/**
 * Represents a single patient currently in the hospital simulation.
 * Contains identification, medical status, current location, risk scores, and timing information.
 * Used throughout the app wherever individual patient data is displayed or analyzed.
 */
export interface Patient {
  patient_id: string;
  name: string;
  age: number;
  arrival_time: number;
  severity: Severity;
  state: PatientState;
  current_department: DepartmentKey | "registration" | "triage";
  chief_complaint: string;
  risk_score: number;
  total_wait_time: number;
  pathway: PatientPathway;
  timing: {
    triage_start?: number;
    er_start?: number;
    labs_start?: number;
    imaging_start?: number;
    icu_start?: number;
    ward_start?: number;
    discharge_time?: number;
  };
  deterioration_alert?: boolean;
  sepsis_risk?: boolean;
  boarding?: boolean;
  sla_breached?: boolean;
}

/**
 * Represents the real-time operational state of a single hospital department (e.g. ER, ICU).
 * Includes occupancy, queue length, wait times, bed counts, and current status level.
 * Used in the floor plan, digital twin graph, and department status panels.
 */
export interface DepartmentState {
  name: string;
  display_name: string;
  occupancy: number;
  queue_length: number;
  avg_wait_time: number;
  current_patients: number;
  capacity: number;
  beds_available: number;
  status: DepartmentStatus;
  patients_in: string[];
  patients_queued: string[];
  resource_utilization: number;
  burnout_risk?: boolean;
  boarding_count?: number;
}

/**
 * A snapshot of key performance metrics for the entire hospital at a given simulation moment.
 * Includes wait times, utilization rates, patient counts, and risk indicators like diversion risk and SLA compliance.
 * Used in MetricCard displays, the AI Copilot radar chart, and the shift-report page.
 */
export interface HospitalMetrics {
  sim_time: number;
  avg_wait_time: number;
  active_patients: number;
  discharged_today: number;
  total_admitted: number;
  throughput_per_hour: number;
  bed_utilization: number;
  icu_utilization: number;
  er_utilization: number;
  ward_utilization: number;
  staff_utilization: number;
  critical_patients: number;
  mortality_risk_index: number;
  alerts_active: number;
  severity_counts?: { critical: number; high: number; medium: number; low: number };
  boarding_count?: number;
  deteriorating_count?: number;
  sepsis_count?: number;
  sla_compliance?: number;
  diversion_risk?: number;
  minutes_to_diversion?: number;
  delay_cost_per_hour?: number;
}

/**
 * Represents a single point in the 24-hour patient arrival forecast.
 * Used to predict how busy the hospital will be in the coming hours.
 */
export interface ForecastPoint {
  hour_offset: number;
  hour_of_day: number;
  predicted_arrivals: number;
  staffing_capacity: number;
}

/**
 * Represents a real-time alert generated by the simulation when a threshold is exceeded.
 * Alerts are displayed in the Command Center's alerts panel and in the DiversionBanner.
 */
export interface HospitalAlert {
  alert_id: string;
  severity: AlertSeverity;
  department: string;
  message: string;
  timestamp: number;
}

/**
 * Tracks how many patients are actively moving between each pair of departments.
 * Each field is a count of patients currently in transit along that specific route.
 * Used in the Digital Twin page to draw and label the arrows between department nodes.
 */
export interface PatientFlow {
  registration_to_er: number;
  er_to_labs: number;
  er_to_imaging: number;
  er_to_icu: number;
  er_to_ward: number;
  er_to_discharge: number;
  labs_to_imaging: number;
  labs_to_ward: number;
  imaging_to_icu: number;
  imaging_to_ward: number;
  icu_to_ward: number;
  ward_to_discharge: number;
}

/**
 * Holds the current runtime configuration for the hospital simulation.
 * Includes patient arrival rate and flags for active crisis events like flu outbreaks or equipment failures.
 * Sent to the backend via WebSocket to change how the simulation behaves.
 */
export interface SimulationConfig {
  arrival_rate: number;
  flu_outbreak: boolean;
  ct_failure: boolean;
  mri_failure: boolean;
  lab_slowdown: boolean;
  mass_casualty: boolean;
  heatwave: boolean;
  covid_surge: boolean;
}

export type SpecialistStatus = "available" | "busy" | "in_surgery";

/**
 * Represents a medical specialist (e.g. cardiologist, surgeon) who can be assigned to patients.
 * Tracks their current status, workload, and how soon they will be available.
 * Displayed in the Operations Hub specialist grid.
 */
export interface Specialist {
  specialist_id: string;
  name: string;
  specialty: string;
  role: string;
  avg_consult_min: number;
  patient_load: number;
  queue_length: number;
  available_in_min: number;
  status: SpecialistStatus;
  current_assignment: string;
}

export type BottleneckType =
  | "Doctor" | "Specialist" | "Operating Room" | "Equipment" | "Bed" | "Nurse";

/**
 * Represents a manually-entered operational constraint that the optimizer must not move or reassign.
 * For example, a surgeon in the middle of an operation, or equipment that is currently offline.
 * Displayed and managed in the Operations Hub fixed constraints panel.
 */
export interface FixedBottleneck {
  bottleneck_id: string;
  resource_name: string;
  resource_type: BottleneckType;
  status: string;
  priority: "low" | "medium" | "high" | "critical";
  notes: string;
  start_label: string;
  release_label: string;
  release_in_min: number | null;
  active: boolean;
}

/**
 * An AI-generated care recommendation for a specific tracked patient.
 * Includes the action to take, the reasons for it, predicted improvements, and whether it is currently blocked.
 * Displayed in the Patient Intelligence page inside each TrackedCard.
 */
export interface CareRecommendation {
  title: string;
  reasons: string[];
  deterioration_reduction: number;
  throughput_improvement: number;
  blocked: boolean;
  alternative: string | null;
  urgency: "critical" | "high" | "moderate" | "low";
}

/**
 * A high-acuity patient being actively monitored by the care coordination system.
 * Extends basic patient data with specialist assignment, care pathway, risk percentage, and an AI recommendation.
 * Used in the Patient Intelligence page to render the TrackedCard component.
 */
export interface TrackedPatient {
  patient_id: string;
  name: string;
  age: number;
  condition: string;
  chief_complaint: string;
  severity: Severity;
  priority: "critical" | "high" | "moderate" | "low";
  awaiting_specialty: string;
  preferred_role: string;
  ed_wait_min: number;
  total_wait_time: number;
  target_window_min: number;
  over_target: boolean;
  over_target_min: number;
  risk_score: number;
  risk_pct: number;
  pathway: string[];
  specialist: Specialist | null;
  recommendation: CareRecommendation;
}

/**
 * Bundles together the full care coordination snapshot: specialists, fixed bottlenecks, and tracked patients.
 * This is the data structure received from the backend's care coordination service and stored in HospitalState.
 */
export interface CareState {
  specialists: Specialist[];
  bottlenecks: FixedBottleneck[];
  tracked_patients: TrackedPatient[];
}

/**
 * The complete real-time state of the hospital simulation, broadcast by the backend every 0.8 seconds.
 * Contains department states, all patients, aggregated metrics, active alerts, patient flow, and configuration.
 * This is the top-level data type received via WebSocket and stored in simulationStore.
 */
export interface HospitalState {
  type?: string;
  sim_time: number;
  real_timestamp: number;
  departments: Record<DepartmentKey, DepartmentState>;
  patients: Patient[];
  metrics: HospitalMetrics;
  alerts: HospitalAlert[];
  flow: PatientFlow;
  config: SimulationConfig;
  forecast_24h?: ForecastPoint[];
  care?: CareState;
}

/**
 * A compact recording of key hospital metrics at a single point in simulation time.
 * These snapshots are collected over time and stored in simulationStore's metricsHistory array
 * for historical trend charts and before/after comparisons.
 */
export interface MetricsSnapshot {
  sim_time: number;
  avg_wait_time: number;
  active_patients: number;
  throughput_per_hour: number;
  bed_utilization: number;
  icu_utilization: number;
  er_utilization: number;
  staff_utilization: number;
  critical_patients: number;
}

/**
 * A time-series forecast for a specific metric in a specific department.
 * Includes predicted values, confidence bounds, trend direction, and whether a warning threshold will be breached.
 * Used by the AI Copilot to show future demand predictions.
 */
export interface ForecastSeries {
  horizon_minutes: number;
  department: string;
  metric: string;
  timestamps: number[];
  values: number[];
  lower_bound: number[];
  upper_bound: number[];
  trend: "increasing" | "decreasing" | "stable";
  severity: "normal" | "warning" | "critical";
  predicted_peak: number | null;
  predicted_peak_time: number | null;
  confidence: number;
}

/**
 * A prediction that a specific department metric will breach a critical threshold within the next few minutes.
 * Used in the AI Copilot's "Predicted Bottlenecks" sidebar to warn operators before a crisis occurs.
 */
export interface BottleneckPrediction {
  department: string;
  dept_key: DepartmentKey;
  metric: string;
  current_value: number;
  threshold: number;
  predicted_breach: number;
  eta_minutes: number;
  confidence: number;
  severity: "info" | "warning" | "critical";
  queue_length: number;
  trend_direction: "increasing" | "stable";
}

/**
 * A single staffing change recommendation produced by the optimization engine.
 * Specifies how many of a given resource type should be allocated to a department, and why.
 * Displayed in the AI Copilot's "Staff Reallocation" table.
 */
export interface StaffingRecommendation {
  department: string;
  resource_type: string;
  current: number;
  recommended: number;
  delta: number;
  impact_score: number;
  reason: string;
  urgency: "low" | "medium" | "high" | "critical";
}

/**
 * The complete output from the OR-Tools (or SciPy fallback) optimization engine.
 * Includes staffing recommendations, predicted improvements, root causes, an intervention plan,
 * and optionally an AI-generated narrative explanation.
 * Used in the AI Copilot page and stored in simulationStore.
 */
export interface OptimizationResult {
  objective_value: number;
  recommendations: StaffingRecommendation[];
  predicted_wait_reduction: number;
  predicted_throughput_increase: number;
  predicted_utilization_improvement: number;
  bottleneck_department: string;
  bottleneck_metric: string;
  bottleneck_severity: string;
  root_causes: string[];
  intervention_plan: string[];
  confidence: number;
  solver: string;
  ai_narrative?: {
    narrative: string;
    model: string;
    predicted_outcomes: {
      wait_reduction: number;
      throughput_increase: number;
      utilization_improvement: number;
    };
  };
}

/**
 * The full AI Copilot analysis response returned by the backend's /ai/analysis endpoint.
 * Bundles together the natural-language explanation, the optimization result, bottleneck predictions, and forecast series.
 * Used in the CopilotPage component to populate every analysis panel.
 */
export interface CopilotAnalysis {
  explanation: {
    explanation: string;
    model: string;
    generated: boolean;
    bottleneck_department: string;
    severity: string;
  };
  optimization: OptimizationResult;
  bottleneck_predictions: BottleneckPrediction[];
  forecast_summary: Record<string, ForecastSeries>;
}

export type EventType =
  | "flu_outbreak" | "ct_failure" | "mri_failure" | "lab_slowdown"
  | "mass_casualty" | "heatwave" | "covid_surge" | "staff_shortage"
  | "clear_event";

/**
 * The full set of configurable parameters for the Simulation Sandbox page.
 * Includes staffing levels, resource counts, and which crisis events are currently active.
 * Sent to the backend when the user adjusts sliders or toggles events.
 */
export interface SandboxConfig {
  arrival_rate: number;
  er_beds: number;
  er_doctors: number;
  er_nurses: number;
  lab_technicians: number;
  lab_analyzers: number;
  imaging_ct: number;
  imaging_mri: number;
  icu_beds: number;
  icu_doctors: number;
  icu_nurses: number;
  ward_beds: number;
  ward_doctors: number;
  ward_nurses: number;
  active_events: EventType[];
}

/**
 * Holds a before-and-after metrics comparison between a baseline scenario and an optimized one.
 * The improvements record maps metric names to their percentage improvements.
 * Used to show the impact of applying the AI optimization recommendations.
 */
export interface ComparisonMetrics {
  baseline: Partial<HospitalMetrics>;
  optimized: Partial<HospitalMetrics>;
  improvements: Record<string, number>;
}
